In [2]:
import numpy as np
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d.shape
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [4]:
arr2d[2]

array([7, 8, 9])

In [5]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])