In [2]:
import numpy as np
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d.shape
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [4]:
arr2d[2]

array([7, 8, 9])

In [5]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
#統計使用實體方法
arr = np.random.randint(50,101,size=(10,5))
arr.sum()
arr.sum(0)
arr.sum(axis=1)

array([352, 367, 399, 427, 305, 367, 407, 432, 302, 361])

In [12]:
#使用numpy內的function
arr = np.random.randint(50,101,size=(10,5))
np.sum(arr)
np.sum(arr,axis=0)
np.sum(arr,axis=1)


array([356, 364, 382, 427, 368, 376, 351, 394, 417, 409])

In [ ]:
#常用的統計方法
#sum
#mean
#std
#max
#min
#median