In [3]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [4]:
array2 = np.array([9, 8, 7, 6, 5])
array2

array([9, 8, 7, 6, 5])

In [8]:
array3 = array1 + array2
array4 = array3 * 10
array4 / 10

array([10., 10., 10., 10., 10.])